[toolchain]
package_manager = "yarn"
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = true

[programs.localnet]
sodap = "4eLJ3QGiNrPN6UUr2fNxq6tUZqFdBMVpXkL2MhsKNriv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"

[test.validator]
reset = true
